import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";
import Counter from "@/components/counter.js";
import Userform from "@/components/Userform";
import DaddyComponent from "@/components/DaddyComponent";
import Children from "@/components/Children";
import TaskList from "@/components/TaskList";

export default function Home() {
  return (
    // Fragment - Envolve as tags que contém o conteúdo do site
    <>
      <Head>
        <title>Fundamento do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World! Meu primeiro site em React!</h1>
        <Welcome />
        <User />
        {/* Componente fcom desestruturação de props */}
        <Description city="Registro" age={18} email="paulo@email.com" />
        <Pet name="Rex" breed="Dinossaur" age={3}/>
        {/* Importando o contador(utilizando estados) */}
        <br />
        <Counter />
        <br />
        <Userform />
        <br />
        <br />
        <DaddyComponent/>
        <br />
        <br />
        <Children>
          <div>
            <p>Este é o conteúdo da children</p>
          </div>
        </Children>
        <br />
        <br />
        <TaskList 
        tasks ={[
          {
            id: "1",
            text: "Pagar contas"
          },
          {
            id: "2",
            text: "Fazer compras no mercado"
          },
          {
            id: "3",
            text: "Lavar o carro"
          },
          {
            id: "4",
            text: "Estudar React"
          },
        ]}
        />
      </main>
    </>
  );
}
